### ISSUE TITLE
may you share the CSL dataset

### ISSUE THREAD

**Issue by Hammer-888** [hulianyuyy/SEN_CSLR#1]
as title, maybe Baidu Netdisk link， thanks a lot.

**Comment by hulianyuyy** [comment]
Sorry, but according to the data release agreement that i signed, i can't share the data by my own. You could follow this [web](https://ustc-slr.github.io/openresources/cslr-dataset-2015/index.html) to request the data.

**Comment by Hammer-888** [comment]
I got the datasets, but  i have some trouble in **data_preprocess-CSL.py** . how can i get the tran.txt, dev.txt, and voc.txt.
And thanks a lot,

**Comment by hulianyuyy** [comment]
[train.txt](https://drive.google.com/file/d/1oKsHolNukOhwTiWbG4RT2WBS2FacazE3/view?usp=share_link), [dev.txt](https://drive.google.com/file/d/1oKsHolNukOhwTiWbG4RT2WBS2FacazE3/view?usp=share_link) and [voc.txt](https://drive.google.com/file/d/165wseb7HvQahc6OO20GDkp_1jIAQmZuS/view?usp=share_link) are here.

**Comment by Hammer-888** [comment]
thanks for your relply,I mean that i get the CSL_Continuous data just contains videos and a corpus.txt. But in data_preprocess-CSL.py your datas all endwith .jpg. If you do some pre-process, would you mind to share it, and thanks again.
![image](https://user-images.githubusercontent.com/82921242/222949144-d57bc498-bc3a-446d-801e-bb3254afd787.png)

**Comment by Hammer-888** [comment]
![image](https://user-images.githubusercontent.com/82921242/222949366-b19a5f56-de14-401d-b308-b9a2c5f44204.png)
supplementary

**Comment by hulianyuyy** [comment]
The data i got is consisted of .jpg files.  I also notice that the video names of yours are not the same with mine. I suspect that they have changed over time, but with the same contents. Maybe you should rewrite the data-preprocess.py according to the label file you get.

**Comment by Hammer-888** [comment]
Thanks for sharing ! Expect the following works.In addition, if now you shares jpgs data  is not breach of release agreement when i have access to got the video data. 
email : creepui@gmail.com
