### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ffly666** [hulianyuyy/SEN_CSLR#10]
An error is reported after executing this naming.

<img width="499" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/61150ac4-e657-4a22-ba8f-005180cb2200">

<img width="665" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/2f38027e-f3d3-4f54-a984-32389ae4a5a3">

**Comment by ffly666** [comment]
<img width="1079" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/7c5c7fa0-c03e-41b9-955c-6b10b429dfbd">

**Comment by ffly666** [comment]
clip is none

**Comment by hulianyuyy** [comment]
This is a common issue. You may check the link to the dataset path. You haven't loaded the dataset into the memory successfully.

**Comment by ffly666** [comment]
Hello,There is also a problem with this。I wonder why this gloss_dict variable is None
<img width="1107" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/ee6d60ea-3d87-48d6-a286-e574593ccec3">
<img width="959" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/c88e8b27-4539-4a33-a00f-202d4bd7c8c9">

**Comment by ffly666** [comment]
Hello, I want to know what device you are, my 32G video memory is bursting
<img width="1102" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/b2df9f5f-e28a-489b-805b-9e07578e5107">

**Comment by hulianyuyy** [comment]
I have re-uploaded the test_one_video.py by fixing some error. You may get correct outputs here. It costs about 8G memory.

**Comment by ffly666** [comment]
> I have re-uploaded the test_one_video.py by fixing some error. You may get correct outputs here. It costs about 8G memory.

Thank you, the model is already running
