### ISSUE TITLE
Spatial Attention Network

### ISSUE THREAD

**Issue by atonyo11** [hulianyuyy/SEN_CSLR#11]
Was the Spatial Attention Network, such as SENet or ECA-Net as mentioned in the paper, tried as a backbone before implementing SEN_CSLR? If so, did the results improve?

**Comment by hulianyuyy** [comment]
We have tried SENet, as shown in tab.5 in our paper, and find the results slightly improve by 0.5% & 0.7% on the Dev and Test sets, respectively. As for ECA-Net, we haven't implemented it by now.

**Comment by atonyo11** [comment]
I got it. Thank you!
