### ISSUE TITLE
warp-ctc能否代替ctcdecode?

### ISSUE THREAD

**Issue by Uily1YUT** [hulianyuyy/SEN_CSLR#14]
能否用warp-ctc完全按代替ctcdecode部分呢？因为我看到在VAC_CSLR的repo中看到[Optional] [SeanNaren/warp-ctc](https://github.com/SeanNaren/warp-ctc) At the beginning of this research, we adopt warp-ctc for supervision, and we recently find that pytorch version CTC can reach similar results.但还没有进一步验证。

**Comment by hulianyuyy** [comment]
warp-ctc和ctcdecode是两个不同的部分。warp-ctc用于训练时添加ctc loss，ctcdecode用于测试时进行ctc解码。在我们较新的工作如[CorrNet](https://github.com/hulianyuyy/CorrNet)和[CorrNet+](https://github.com/hulianyuyy/CorrNet_Plus)中，也不再使用warp-ctc，而是直接使用pytorch自带的ctc loss，但是ctcdecode仍是必需的。
