### ISSUE TITLE
CSL dataset Trained checkpoint

### ISSUE THREAD

**Issue by Hammer-888** [hulianyuyy/SEN_CSLR#3]
hi, me again, may you upload  CSL dataset Trained checkpoint, thanks

**Comment by hulianyuyy** [comment]
As there are some tricks to handle this dataset, we leave it for future plan. You can refer to this issue [here](https://github.com/ycmin95/VAC_CSLR/issues/17#issuecomment-1150881035).

**Comment by Hammer-888** [comment]
And how to generate attention heat map in SEN? Thanks

**Comment by hulianyuyy** [comment]
We follow [Grad-CAM](https://github.com/ramprs/grad-cam/) to generate the class activation maps of the last layer of SEN as attention heat maps. I just upload the 'generate_cam.py' and you may use it to generate the attention maps.

**Comment by zxyonaroll** [comment]
> 
If I'm understanding correctly, the way data is handled shouldn't be a topic so difficult to discuss publicly that it might as well be written in Martian language!

**Comment by hulianyuyy** [comment]
Sorry, i can't fully understand your question. What does 'the way data is handled' refer to?

**Comment by zxyonaroll** [comment]
> We follow [Grad-CAM](https://github.com/ramprs/grad-cam/) to generate the class activation maps of the last layer of SEN as attention heat maps. I just upload the 'generate_cam.py' and you may use it to generate the attention maps.

Sorry for my relpying at the wrong place
