### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by xiaoshimeng** [hulianyuyy/SEN_CSLR#5]
Hello, I have trained SEN-CSLR on the data set of CSL-Daily, but WER has not reached 31.1% and 30.7% as mentioned in the article, which is about 1% short. May I ask which part needs to be modified?

**Comment by hulianyuyy** [comment]
You may choose to reduce the lr by half from 0.0001 to 0.00005, and change the lr deacying rate (gamma in the 'optimizer.py') from 0.2 to 0.5.

**Comment by xiaoshimeng** [comment]
Hello, I would like to ask whether the final evaluation indicators calculated by sclite and python_wer provided by the project will have a big difference between them.

**Comment by hulianyuyy** [comment]
I haven't used thee python_wer evaluation tool. Ideally they should have the same results. Do you transfer it from the newest VAC reepo?

**Comment by xiaoshimeng** [comment]
Yes，I transfer it from the newest VAC reepo.

**Comment by hulianyuyy** [comment]
Sorry, but i know little about the python_wer module. You may compare its performance on the VAC repo as well.

**Comment by xiaoshimeng** [comment]
Under this path: ./evaluation/python_wer_evaluation.py  and ./evaluation/wer_calculation.py
