### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by xxxiaosong** [hulianyuyy/SEN_CSLR#7]
Hello! The following issues were encountered during the training process. Could you give me some guidance？
![image](https://github.com/hulianyuyy/SEN_CSLR/assets/136720538/345d229f-f37e-43e6-b2df-e51d54ad1631)

**Comment by hulianyuyy** [comment]
It seems that you haven't correctly linked the dataset to the required place. You can create a link as suggested in the readme.md.

**Comment by xxxiaosong** [comment]
Thank you for your reply! The dataset soft link seems to be successful because I can preprocess the dataset.

**Comment by hulianyuyy** [comment]
According to the information in your screenshot, the model fails to read the sign language images and raises an error "list index out of range". To locate the issue, you can check the type of the input data in the dataloader_video.py by 'print(type(video))' after line 107. You will mostly get a None output. Call me if you have further problems.

**Comment by xxxiaosong** [comment]
Thank you for your reply! The problem has been resolved. I used an RTX3080 with 10GB memory for training, and in order to prevent OOM, I set the batchsize to 1. However, after the first epoch ended, the following error occurred, and I suspect it was OOM again. 
![image](https://github.com/hulianyuyy/SEN_CSLR/assets/136720538/02f345f4-06da-489b-b9d8-36c6f871306c)

**Comment by hulianyuyy** [comment]
It seems that you don't have enough space on the disk.



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 28, 2023 10:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/SEN_CSLR] Train problem (Issue #7)




 
Thank you for your reply! The problem has been resolved. I used an RTX3080 with 10GB memory for training, and in order to prevent OOM, I set the batchsize to 1. However, after the first epoch ended, the following error occurred, and I suspect it was OOM again.

**Comment by xxxiaosong** [comment]
Thank you for your reply! Not due to insufficient disk space. The problem has been resolved as follows: 
[https://github.com/parlance/ctcdecode/issues/124](url)

**Comment by hulianyuyy** [comment]
Many thanks. Hope you can enjoy the work!



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 29, 2023 17:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/SEN_CSLR] Train problem (Issue #7)




 
Thank you for your reply! Not due to insufficient disk space. The problem has been resolved as follows:
 https://github.com/parlance/ctcdecode/issues/124

**Comment by xxxiaosong** [comment]
Hello! I am here again. I have replaced a new device to run this project. But I have encountered some inexplicable errors. The error message is as follows.
![image](https://github.com/hulianyuyy/SEN_CSLR/assets/136720538/02d31161-cb56-43cb-892b-0863d9b367e1)
![image](https://github.com/hulianyuyy/SEN_CSLR/assets/136720538/4e18beb9-350d-48b6-88e3-b2f29bff93f7)
Could you give me some guidance？

**Comment by hulianyuyy** [comment]
I don't have exact answers, but i figure that this may be attributed to that you may set a different number of classes with the target datasets? This issus may be related with the number of classes.

**Comment by xxxiaosong** [comment]
Thank you for your reply. The problem has been resolved. This is the problem with sclite. I have another question, can I execute the following command to continue training with the saved weights when my training process unexpectedly terminates.

python main.py --load-weights work_dir/baseline_res18/dev_23.60_epoch15_model.pt

**Comment by hulianyuyy** [comment]
You may use "python main.py --load-checkpoints&nbsp; work_dir/baseline_res18/dev_23.60_epoch15_model.pt"



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 21, 2023 14:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/SEN_CSLR] Train problem (Issue #7)




 
Thank you for your reply. The problem has been resolved. This is the problem with sclite. I have another question, can I execute the following command to continue training with the saved weights when my training process unexpectedly terminates.
 
python main.py --load-weights work_dir/baseline_res18/dev_23.60_epoch15_model.pt

**Comment by xxxiaosong** [comment]
Haha. Thank you. I used the wrong command.

**Comment by youthxin** [comment]
> Thank you for your reply! Not due to insufficient disk space. The problem has been resolved as follows: [https://github.com/parlance/ctcdecode/issues/124](url)

Hello, I have also encountered such a problem. The link is invalid. How was it resolved

**Comment by hulianyuyy** [comment]
You 

> > Thank you for your reply! Not due to insufficient disk space. The problem has been resolved as follows: [https://github.com/parlance/ctcdecode/issues/124](url)
> 
> Hello, I have also encountered such a problem. The link is invalid. How was it resolved

You may refer to this [issue](https://github.com/parlance/ctcdecode/issues/124) and [this](https://github.com/hulianyuyy/CorrNet/issues/19).

**Comment by youthxin** [comment]
> You
> 
> > > Thank you for your reply! Not due to insufficient disk space. The problem has been resolved as follows: [https://github.com/parlance/ctcdecode/issues/124](url)
> > 
> > 
> > Hello, I have also encountered such a problem. The link is invalid. How was it resolved
> 
> You may refer to this [issue](https://github.com/parlance/ctcdecode/issues/124) and [this](https://github.com/hulianyuyy/CorrNet/issues/19).

Thank you very much for taking the time to reply to me. I will try it out
