### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ffly666** [hulianyuyy/SEN_CSLR#8]
<img width="878" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/816071cc-bdcc-46f0-826b-9476692655d5">

**Comment by ffly666** [comment]
请问这个报错是怎么回事？

**Comment by ffly666** [comment]
<img width="902" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/ee92c7dd-5366-4673-b335-1db2ba528045">

**Comment by hulianyuyy** [comment]
You may change the device into "0" in line 12 in the baseline.yaml.

**Comment by ffly666** [comment]
I have modified the file the way you did and then run it with the same error.
This is my version of Torch。
<img width="455" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/1792472f-ff55-4b76-bd22-be1d364b80a0">
This is my error.
<img width="880" alt="image" src="https://github.com/hulianyuyy/SEN_CSLR/assets/100413814/59982b32-47a0-4941-bf75-59200a9211e8">

**Comment by hulianyuyy** [comment]
I think this can be attributed from that you assigned an non-existed gpu id for the code. You may try running "python main.py --device 0 --phase test"?

**Comment by ffly666** [comment]
> 

Thank you, I changed the environment and solved, this problem.
